name: photo_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  url_launcher: ^6.3.2
  http: ^1.6.0
  flutter_riverpod: ^3.0.3
  page_transition: ^2.2.1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  dio: ^5.7.0
  logger: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2

  firebase_core: ^3.0.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.10

  flutter_lints: ^5.0.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  retrofit_generator: ^10.2.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutterfire_cli: ^1.3.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900